# Generated by Django 4.2.29 on 2026-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_compliance_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_paid_at_b40014_idx',
            old_name='payments_pa_paid_at_855e3d_idx',
        ),
        migrations.RenameIndex(
            model_name='stripeevent',
            new_name='payments_st_process_ac07c0_idx',
            old_name='payments_st_processed_700e22_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
