# Generated by Django 4.2.29 on 2026-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodtrucks', '0013_locationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RevenuePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(help_text='Confidence score from 0 to 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foodtruck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_predictions', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Revenue Prediction',
                'verbose_name_plural': 'Revenue Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_score', models.FloatField(help_text='Score from 0 to 100')),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='analytics.event')),
                ('foodtruck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_opportunities', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Event Opportunity',
                'verbose_name_plural': 'Event Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='analytics_e_start_d_494308_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueprediction',
            index=models.Index(fields=['foodtruck', 'date'], name='analytics_r_foodtru_f16647_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueprediction',
            index=models.Index(fields=['-created_at'], name='analytics_r_created_10fc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventopportunity',
            index=models.Index(fields=['foodtruck', 'event'], name='analytics_e_foodtru_d40cba_idx'),
        ),
        migrations.AddIndex(
            model_name='eventopportunity',
            index=models.Index(fields=['-created_at'], name='analytics_e_created_a8bb58_idx'),
        ),
    ]
