# Generated by Django 4.2.29 on 2026-05-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_openagendasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=32)),
                ('model_name', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(db_index=True, max_length=16)),
                ('raw_response', models.JSONField()),
                ('normalized_data', models.JSONField()),
                ('confidence_score', models.FloatField(help_text='Confidence returned by the AI, 0.0–1.0')),
                ('analyzed_at', models.DateTimeField(db_index=True)),
                ('processing_time_ms', models.PositiveIntegerField()),
                ('token_usage_input', models.PositiveIntegerField()),
                ('token_usage_output', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='analytics.event')),
            ],
            options={
                'verbose_name': 'Event AI Analysis',
                'verbose_name_plural': 'Event AI Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['provider', 'model_name'], name='analytics_e_provide_88b2c8_idx'), models.Index(fields=['prompt_version'], name='analytics_e_prompt__270efd_idx'), models.Index(fields=['-analyzed_at'], name='analytics_e_analyze_e05d85_idx')],
            },
        ),
    ]
