# Generated by Django 4.2.29 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_event_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
