# Generated by Django 4.2.29 on 2026-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_created_5f768f_idx',
            old_name='common_audi_created_75f4b8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_action_f07e2b_idx',
            old_name='common_audi_action_71fe78_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_model_33fcaa_idx',
            old_name='common_audi_model_1a1592_idx',
        ),
    ]
