# Generated by Django 4.2.29 on 2026-04-16 15:31

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


def create_default_tax(apps, schema_editor):
    Tax = apps.get_model('common', 'Tax')
    if Tax.objects.filter(is_default=True).exists():
        return

    Tax.objects.create(
        name='TVA 10%',
        rate=Decimal('0.1000'),
        is_default=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_common_audi_created_75f4b8_idx_common_audi_created_5f768f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', Decimal('0.0000')), ('rate__lte', Decimal('1.0000'))), name='common_tax_rate_between_zero_and_one'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='common_single_default_tax'),
        ),
        migrations.RunPython(create_default_tax, migrations.RunPython.noop),
    ]
