# Generated by Django 4.2.29 on 2026-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tax_tax_common_tax_rate_between_zero_and_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country', '-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
