# Generated by Django 4.2.29 on 2026-04-03 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food truck', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the food truck')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the food truck is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the food truck was created')),
                ('logo', models.ImageField(blank=True, help_text='Logo image for the food truck', null=True, upload_to='foodtrucks/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the food truck', null=True, upload_to='foodtrucks/covers/')),
                ('primary_color', models.CharField(default='#000000', help_text='Primary brand color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', help_text='Secondary brand color (hex code)', max_length=7)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('owner', models.ForeignKey(help_text='The user who owns this food truck', on_delete=django.db.models.deletion.CASCADE, related_name='foodtrucks', to=settings.AUTH_USER_MODEL)),
                ('supported_preferences', models.ManyToManyField(blank=True, help_text='Dietary preferences this food truck supports', to='preferences.preference')),
            ],
            options={
                'verbose_name': 'Food Truck',
                'verbose_name_plural': 'Food Trucks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='foodtrucks__is_acti_bda0b2_idx')],
            },
        ),
    ]
