# Generated by Django 4.2.29 on 2026-04-03 12:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the plan', max_length=100)),
                ('code', models.CharField(help_text='Unique code identifier for the plan', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price of the plan', max_digits=10)),
                ('allows_ordering', models.BooleanField(default=False, help_text='Whether this plan allows accepting orders')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the plan was created')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the subscription', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the subscription started')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the subscription ends (null for ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created')),
                ('food_truck', models.OneToOneField(help_text='The food truck this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodtrucks.foodtruck')),
                ('plan', models.ForeignKey(help_text='The plan this subscription is for', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='foodtrucks.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='foodtrucks__status_2f1004_idx'), models.Index(fields=['end_date'], name='foodtrucks__end_dat_2751a4_idx')],
            },
        ),
    ]
