# Generated by Django 4.2.29 on 2026-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0003_foodtruck_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly resource slug', max_length=255, unique=True),
        ),
    ]
