# Generated by Django 4.2.29 on 2026-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0005_foodtruck_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether Stripe charges are enabled'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account id for seller payouts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False, help_text='Whether Stripe account details were submitted'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether seller onboarding is complete'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether Stripe payouts are enabled'),
        ),
        migrations.AddIndex(
            model_name='foodtruck',
            index=models.Index(fields=['stripe_connect_account_id'], name='foodtrucks__stripe__d745b4_idx'),
        ),
    ]