# Generated by Django 4.2.29 on 2026-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0012_foodtruck_price_display_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('score', models.FloatField(help_text='Global score from 0 to 100')),
                ('demand_score', models.FloatField(help_text='Demand sub-score from 0 to 100')),
                ('competition_score', models.FloatField(help_text='Competition sub-score from 0 to 100')),
                ('event_score', models.FloatField(help_text='Event sub-score from 0 to 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foodtruck', models.ForeignKey(help_text='Food truck this location score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location_scores', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Location Score',
                'verbose_name_plural': 'Location Scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['foodtruck', '-created_at'], name='foodtrucks__foodtru_d7d36b_idx'), models.Index(fields=['latitude', 'longitude'], name='foodtrucks__latitud_739301_idx')],
            },
        ),
    ]
