# Generated by Django 4.2.29 on 2026-04-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('free_option', 'Free Option'), ('paid_option', 'Paid Option'), ('bundle', 'Bundle'), ('pricing', 'Pricing')], help_text='Type of recommendation', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured recommendation data (varies by type)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the recommendation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the recommendation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the recommendation was last updated')),
                ('item', models.ForeignKey(help_text='The menu item this recommendation is for', on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='menu.item')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'status'], name='ai_menu_air_item_id_81292c_idx'), models.Index(fields=['recommendation_type', 'status'], name='ai_menu_air_recomme_04a0ff_idx'), models.Index(fields=['status', '-created_at'], name='ai_menu_air_status_7c51ca_idx'), models.Index(fields=['-created_at'], name='ai_menu_air_created_f4b773_idx')],
            },
        ),
    ]
