# Generated by Django 4.2.29 on 2026-04-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text input from user (e.g., copied from Instagram, website)')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of uploaded image file paths or URLs')),
                ('source_url', models.URLField(blank=True, help_text='Optional reference URL (not scraped automatically)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted by AI processing')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when import was created')),
                ('user', models.ForeignKey(help_text='User who initiated the import', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Import',
                'verbose_name_plural': 'Onboarding Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
