# Generated by Django 4.2.29 on 2026-04-07 13:23

from django.db import migrations, models
import django.db.models.deletion
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingimport',
            name='images',
        ),
        migrations.CreateModel(
            name='OnboardingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=onboarding.models.onboarding_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='onboarding.onboardingimport')),
            ],
            options={
                'verbose_name': 'Onboarding Image',
                'verbose_name_plural': 'Onboarding Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingimport',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Uploaded images for AI processing', related_name='imports', to='onboarding.onboardingimage'),
        ),
    ]
