# Generated by Django 4.2.29 on 2026-04-03 12:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
        ('foodtrucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the item')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price of the item', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the item is available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('category', models.ForeignKey(help_text='The category this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
                ('compatible_preferences', models.ManyToManyField(blank=True, help_text='Dietary preferences this item is compatible with', to='preferences.preference')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the option group', max_length=200)),
                ('required', models.BooleanField(default=False, help_text='Whether this group is required')),
                ('min_choices', models.PositiveIntegerField(default=0, help_text='Minimum number of choices required')),
                ('max_choices', models.PositiveIntegerField(blank=True, help_text='Maximum number of choices allowed (null for unlimited)', null=True)),
                ('item', models.ForeignKey(help_text='The item this option group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='menu.item')),
            ],
            options={
                'verbose_name': 'Option Group',
                'verbose_name_plural': 'Option Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the option', max_length=200)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price modifier for this option (can be negative)', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the option is available')),
                ('group', models.ForeignKey(help_text='The option group this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.optiongroup')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the menu is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the menu was created')),
                ('food_truck', models.ForeignKey(help_text='The food truck this menu belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(help_text='The menu this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menu'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available'], name='menu_item_is_avai_85c7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='menu_item_categor_ab58f2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['menu'], name='menu_catego_menu_id_9e0c5c_idx'),
        ),
    ]
