# Generated by Django 4.2.29 on 2026-04-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the combo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the combo')),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Explicit combo price when known', max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the combo is available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('category', models.ForeignKey(help_text='The category this combo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='menu.category')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name of the combo component', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this component in the combo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('combo', models.ForeignKey(help_text='The combo this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='menu.combo')),
                ('item', models.ForeignKey(blank=True, help_text='Resolved menu item for this combo component when available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_memberships', to='menu.item')),
            ],
            options={
                'verbose_name': 'Combo Item',
                'verbose_name_plural': 'Combo Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['category'], name='menu_combo_categor_74695e_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_available'], name='menu_combo_is_avai_20612b_idx'),
        ),
    ]
