# Generated by Django 4.2.29 on 2026-04-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tax_tax_common_tax_rate_between_zero_and_one_and_more'),
        ('menu', '0002_combo_comboitem_combo_menu_combo_categor_74695e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax configuration applied to this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='common.tax'),
        ),
    ]
