# Generated by Django 4.2.29 on 2026-04-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_tax_options_tax_country_tax_is_active'),
        ('menu', '0003_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax configuration applied to this combo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='common.tax'),
        ),
    ]