# Generated by Django 4.2.29 on 2026-04-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_comboitem_fixed_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Legacy fixed item for this combo component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_memberships', to='menu.item'),
        ),
    ]
