# Generated by Django 4.2.29 on 2026-04-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_comboitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_option_group_links', to='menu.item')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_item_links', to='menu.optiongroup')),
            ],
            options={
                'verbose_name': 'Option Group Item',
                'verbose_name_plural': 'Option Group Items',
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='shared_items',
            field=models.ManyToManyField(blank=True, help_text='Additional items in the same category that can reuse this option group', related_name='shared_option_groups', through='menu.OptionGroupItem', to='menu.item'),
        ),
        migrations.AddConstraint(
            model_name='optiongroupitem',
            constraint=models.UniqueConstraint(fields=('option_group', 'item'), name='option_group_item_unique_link'),
        ),
    ]
