# Generated by Django 4.2.29 on 2026-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_category_option_groups_and_option_item_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_score', models.FloatField(help_text='Confidence score from 0 to 1')),
                ('reason', models.TextField(help_text='Explainable reasoning for this suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(help_text='Item this pricing suggestion targets', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_suggestions', to='menu.item')),
            ],
            options={
                'verbose_name': 'Pricing Suggestion',
                'verbose_name_plural': 'Pricing Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='menu_pricin_item_id_be187c_idx')],
            },
        ),
    ]
