# Generated by Django 4.2.29 on 2026-04-03 12:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('foodtrucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the order', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price of the order', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the order was created')),
                ('customer', models.ForeignKey(help_text='The customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('food_truck', models.ForeignKey(help_text='The food truck for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order', max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (unit_price * quantity)', max_digits=8)),
                ('item', models.ForeignKey(help_text='The menu item', on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time of the pickup slot')),
                ('end_time', models.DateTimeField(help_text='End time of the pickup slot')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of orders for this slot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the slot was created')),
                ('food_truck', models.ForeignKey(help_text='The food truck this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slots', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Pickup Slot',
                'verbose_name_plural': 'Pickup Slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_modifier', models.DecimalField(decimal_places=2, help_text='Price modifier at time of order', max_digits=8)),
                ('option', models.ForeignKey(help_text='The selected option', on_delete=django.db.models.deletion.CASCADE, to='menu.option')),
                ('order_item', models.ForeignKey(help_text='The order item this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Option',
                'verbose_name_plural': 'Order Item Options',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_slot',
            field=models.ForeignKey(help_text='The pickup slot for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.pickupslot'),
        ),
        migrations.AddIndex(
            model_name='pickupslot',
            index=models.Index(fields=['food_truck', 'start_time'], name='orders_pick_food_tr_7a7384_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickupslot',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='pickup_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='orderitemoption',
            constraint=models.CheckConstraint(check=models.Q(('price_modifier__gte', Decimal('-1000.00'))), name='order_item_option_modifier_reasonable'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='order_item_total_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pickup_slot'], name='orders_orde_pickup__f33f61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['food_truck'], name='orders_orde_food_tr_9c5038_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='order_total_price_non_negative'),
        ),
    ]
