# Generated by Django 4.2.29 on 2026-04-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the order was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_slot',
            field=models.ForeignKey(blank=True, help_text='The pickup slot for this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.pickupslot'),
        ),
    ]
