# Generated by Django 4.2.29 on 2026-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the slot was last updated'),
        ),
    ]
