# Generated by Django 4.2.29 on 2026-04-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0004_alter_foodtruck_slug'),
        ('orders', '0005_pickupslot_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday)')),
                ('start_time', models.TimeField(help_text='Window start time')),
                ('end_time', models.TimeField(help_text='Window end time')),
                ('capacity_per_slot', models.PositiveIntegerField(help_text='Capacity per generated slot')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=10, help_text='Duration of each slot in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_truck', models.ForeignKey(help_text='The food truck this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='foodtrucks.foodtruck')),
            ],
            options={
                'verbose_name': 'Service Schedule',
                'verbose_name_plural': 'Service Schedules',
                'ordering': ['food_truck', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='pickupslot',
            name='service_schedule',
            field=models.ForeignKey(blank=True, help_text='Originating service schedule, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_slots', to='orders.serviceschedule'),
        ),
    ]
