# Generated by Django 4.2.29 on 2026-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_service_schedule_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceschedule',
            name='orders_unique_service_schedule_window',
        ),
        migrations.AddConstraint(
            model_name='serviceschedule',
            constraint=models.UniqueConstraint(fields=('food_truck', 'day_of_week', 'start_time', 'end_time'), name='unique_service_schedule_window'),
        ),
    ]
