# Generated by Django 4.2.29 on 2026-04-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0004_alter_foodtruck_slug'),
        ('orders', '0008_remove_serviceschedule_orders_unique_service_schedule_window_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional spot name', max_length=200)),
                ('address_line_1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(help_text='Postal / ZIP code', max_length=20)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('notes', models.TextField(blank=True, help_text='Pickup instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_truck', models.ForeignKey(help_text='Food truck operating at this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='foodtrucks.foodtruck')),
                ('service_schedule', models.OneToOneField(help_text='Service schedule this location describes', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='orders.serviceschedule')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'indexes': [models.Index(fields=['food_truck'], name='orders_loca_food_tr_298451_idx'), models.Index(fields=['latitude', 'longitude'], name='orders_loca_latitud_655527_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), name='location_valid_coordinates'),
        ),
    ]
