# Generated by Django 4.2.29 on 2026-04-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrucks', '0004_alter_foodtruck_slug'),
        ('orders', '0009_location_location_location_valid_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='service_schedule',
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Optional location this schedule takes place at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_schedules', to='orders.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='food_truck',
            field=models.ForeignKey(help_text='Food truck this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='foodtrucks.foodtruck'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
