# Generated by Django 4.2.29 on 2026-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_location_service_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this schedule is currently active'),
        ),
    ]
