# Generated by Django 4.2.29 on 2026-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_serviceschedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this schedule is currently active'),
        ),
    ]
