# Generated by Django 4.2.29 on 2026-04-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_combo_comboitem_combo_menu_combo_categor_74695e_idx_and_more'),
        ('orders', '0012_alter_serviceschedule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, help_text='The menu combo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.combo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='The menu item', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('item__isnull', False), ('combo__isnull', True)), models.Q(('item__isnull', True), ('combo__isnull', False)), _connector='OR'), name='order_item_exactly_one_product'),
        ),
    ]
