# Generated by Django 4.2.29 on 2026-04-11 00:00

from django.db import migrations, models


def migrate_legacy_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    Order.objects.filter(status='submitted').update(status='pending')
    Order.objects.filter(status='paid').update(status='completed')


def reverse_legacy_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    Order.objects.filter(status='pending').update(status='submitted')
    Order.objects.filter(status='completed').update(status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_combo_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('preparing', 'Preparing'),
                    ('ready', 'Ready'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='draft',
                help_text='Current status of the order',
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_legacy_order_statuses, reverse_legacy_order_statuses),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_25950c_idx'),
        ),
    ]