# Generated by Django 4.2.29 on 2026-04-13 16:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_orde_created_25950c_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_paid_at_8fa0ef_idx',
            old_name='orders_orde_paid_at_70c075_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frozen total tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frozen financial total amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount snapshot for this line', max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage snapshot', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this item including tax', max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='order_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='order_tax_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0)), name='order_item_tax_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='order_item_tax_amount_non_negative'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['number'], name='orders_tick_number_e1f4db_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['issued_at'], name='orders_tick_issued__904275_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='ticket_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='ticket_tax_amount_non_negative'),
        ),
    ]
