# Generated by Django 4.2.29 on 2026-04-16 15:31

from decimal import Decimal
from django.db import migrations, models


def backfill_orderitem_tax_snapshots(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    Tax = apps.get_model('common', 'Tax')

    default_tax = Tax.objects.filter(is_default=True).first() or Tax.objects.first()
    default_rate = getattr(default_tax, 'rate', Decimal('0.1000'))

    for line in OrderItem.objects.all().iterator():
        rate = line.tax_rate
        if rate in (None, Decimal('0.00'), Decimal('0.0000')):
            rate = default_rate
        elif rate > Decimal('1.0000'):
            rate = (rate / Decimal('100')).quantize(Decimal('0.0001'))

        subtotal = (line.unit_price or Decimal('0.00')) * (line.quantity or 0)
        tax_amount = (subtotal * rate).quantize(Decimal('0.01'))
        total_price = (subtotal + tax_amount).quantize(Decimal('0.01'))

        OrderItem.objects.filter(pk=line.pk).update(
            tax_rate=rate,
            tax_amount=tax_amount,
            total_price=total_price,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tax_tax_common_tax_rate_between_zero_and_one_and_more'),
        ('orders', '0016_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tax rate snapshot stored as a fraction', max_digits=6),
        ),
        migrations.RunPython(backfill_orderitem_tax_snapshots, migrations.RunPython.noop),
    ]
